function page(title, description) {
  return { title, description };
}

export const placeholders = {
  home: page('Home', 'Marketing homepage with hero carousel, search widget, and featured cars.'),
  about: page('About Us'),
  fleet: page('Our Fleet'),
  services: page('Services'),
  manpower: page('Manpower'),
  operations: page('Operations'),
  clients: page('Clients'),
  contact: page('Contact'),
  docBrochure: page('Company Brochure'),
  docTradeLicense: page('Trade License'),
  docVatCertificate: page('VAT Certificate'),
  docQuotation: page('Quotation'),
  docInvoice: page('Invoice Sample'),
  docTripSheet: page('Trip Sheet'),
  docPermit: page('Permit'),
  cars: page('Browse Cars', 'Filterable vehicle catalog with shareable URL query params.'),
  carDetail: page('Car Details'),
  carBook: page('Book Vehicle', 'Full booking form for authenticated customers.'),
  myBookings: page('My Bookings'),
  bookingInvoice: page('Booking Invoice'),
  bookingInvoicePdf: page('Booking Invoice PDF'),
  corporateTrips: page('My Corporate Trips'),
  corporateInvoice: page('Corporate Trip Invoice'),
  corporateInvoicePdf: page('Corporate Trip Invoice PDF'),
  login: page('Sign In'),
  register: page('Create Account'),
  logout: page('Signing Out'),
  adminLogin: page('Admin Sign In'),
  adminDashboard: page('Admin Dashboard'),
  adminCars: page('Fleet — Cars'),
  adminCarNew: page('Add Car'),
  adminCarDetail: page('Car Details'),
  adminCarEdit: page('Edit Car'),
  adminDrivers: page('Fleet — Drivers'),
  adminDriverNew: page('Add Driver'),
  adminDriverDetail: page('Driver Details'),
  adminDriverEdit: page('Edit Driver'),
  adminEmployees: page('Fleet — Employees'),
  adminEmployeeNew: page('Add Employee'),
  adminEmployeeDetail: page('Employee Details'),
  adminVendors: page('Fleet — Vendors'),
  adminVendorNew: page('Add Vendor'),
  adminVendorDetail: page('Vendor Details'),
  adminVendorEdit: page('Edit Vendor'),
  adminMaintenance: page('Maintenance'),
  adminInspections: page('Inspections'),
  adminTracking: page('Live Tracking'),
  adminBookings: page('Bookings'),
  adminBookingInvoice: page('Booking Invoice'),
  adminCorporateTrips: page('Corporate Trips'),
  adminCorporateInvoice: page('Corporate Trip Invoice'),
  adminSettlements: page('Settlements'),
  adminSettlementDetail: page('Settlement Details'),
  adminReports: page('Reports'),
  adminReportsVendors: page('Vendor Reports'),
  adminReportsDrivers: page('Driver Reports'),
  adminReviews: page('Reviews'),
  adminUsers: page('Staff & Users'),
  adminAudit: page('Audit Log'),
  adminSettings: page('Settings'),
  adminSettingsCategories: page('Category Masters'),
  adminProfile: page('Admin Profile'),
  vendorLogin: page('Vendor Sign In'),
  vendorDashboard: page('Vendor Dashboard'),
  vendorCars: page('Vendor Cars'),
  vendorDrivers: page('Vendor Drivers'),
  vendorTrips: page('Vendor Trips'),
  vendorSettlements: page('Vendor Settlements'),
  vendorSettlementPdf: page('Settlement PDF'),
  vendorSettlementExcel: page('Settlement Excel'),
  driverLogin: page('Driver Sign In'),
  driverDashboard: page('Driver Dashboard'),
  driverTrips: page('Driver Trips'),
  driverProfile: page('Driver Profile'),
  driverAvailability: page('Driver Availability'),
  driverPassword: page('Change Password'),
};
