export const ROLES = ['ADMIN', 'STAFF', 'VENDOR', 'DRIVER', 'CUSTOMER'];

export const PERMISSIONS = [
  'MANAGE_FLEET',
  'MANAGE_DRIVERS',
  'MANAGE_VENDORS',
  'MANAGE_BOOKINGS',
  'MANAGE_BILLING',
  'VIEW_REPORTS',
  'MANAGE_CONFIG',
  'MANAGE_USERS',
];

export const BOOKING_STATUSES = ['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'];
export const RENTAL_UNITS = ['HOUR', 'DAY', 'MONTH'];

export const TRANSPORT_STATUSES = [
  'REQUESTED',
  'ASSIGNED',
  'CONFIRMED',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED',
];

export const CORPORATE_MEMBER_ROLES = ['BOOKER', 'VIEWER', 'BILLING'];
export const BILLING_ARRANGEMENTS = ['BILL_TO_COMPANY', 'PAY_ON_TRIP', 'PREPAID', 'NOT_SET'];

export const CAR_TYPES = ['HATCHBACK', 'SEDAN', 'SUV', 'MUV', 'LUXURY', 'BIKE'];
export const TRANSMISSIONS = ['MANUAL', 'AUTOMATIC'];
export const FUEL_TYPES = ['PETROL', 'DIESEL', 'ELECTRIC', 'HYBRID', 'CNG'];
export const CAR_STATUSES = ['ACTIVE', 'MAINTENANCE', 'RETIRED'];
export const CAR_OWNERSHIPS = ['OWNED', 'VENDOR'];
